spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xad-xn?useUnicode=true&amp;autoReconnect=true&amp;characterEncoding=utf8mb4
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 20
      max-idle: 10
      max-wait: 60000
      min-idle: 5
      initial-size: 5
  servlet:
    multipart:
      max-file-size: 15MB
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.hjh.entity
  configuration:
    call-setters-on-nulls: true
logging:
  level:
   com:
     hjh:
      dao: debug
  file: myLog.log
server:
  port: 9099
pic:
  UPLOAD_FILE_PATH: c:/ad/pic/
  UPLOAD_FILE_PATH_MAPPING: file:c:/ad/pic/
gt:
  appid: H4zjDXaTZ8AQi28jH7W8b
  appkey: 5qwEltEBmp8NsruEWWk4i9
  appsecret: 9dwndTOzrW5IsSjNZE6qwA
  appmastersecret: oNz2Pq09pE6jl4PlHLXiA9